spring:
  thymeleaf:
   cash: false
   prefix: classpath:/templates/
   suffix: .html

  application:
    name: rocketmq-console

  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

